### ISSUE TITLE
Support ignore case mode "expected"

### ISSUE THREAD

**Issue by azu** [proofdict/proof-dictionary#1]
```yaml
id: 01CF6NR1Q7XWC035B9XJXNB852
description: typo
expected: $1nimation
patterns:
  - /(a)nimation/i
specs:
  - from: Animation
    to: Animation
  - from: CSS Animation
    to: CSS Animation
  - from: CSS animations
    to: CSS animations
tags:
  - noun

```

is not cool syntax. `$1`
